# Generated by Django 4.2.6 on 2023-11-01 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sell', '0002_alter_carsell_options_carsell_mileage_type_choose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsell',
            name='photo1',
            field=models.ImageField(upload_to='media/images/', verbose_name='Main Photo'),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='photo5',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Photo'),
        ),
        migrations.AlterField(
            model_name='carsell',
            name='photo6',
            field=models.ImageField(blank=True, null=True, upload_to='media/images/', verbose_name='Photo'),
        ),
    ]
