# Generated by Django 4.2.6 on 2023-11-06 13:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0002_slider_title2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='slider',
            name='image2',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='slider/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='slider/'),
            preserve_default=False,
        ),
    ]
