# Generated by Django 4.2.6 on 2023-11-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0003_rename_image_slider_image1_slider_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image3',
        ),
    ]
