# Generated by Django 4.2.6 on 2023-11-07 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0004_remove_slider_image3'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='image3',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='logo/'),
            preserve_default=False,
        ),
    ]
