# Generated by Django 4.2.6 on 2023-11-07 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slider', '0005_slider_image3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slider',
            name='image3',
        ),
    ]
