# Generated by Django 4.2.6 on 2023-10-29 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('address', models.CharField(max_length=250, unique=True)),
                ('email', models.EmailField(max_length=250, unique=True)),
                ('created_at', models.DateField()),
                ('slug', models.SlugField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('created_at', models.DateField()),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('hp', models.PositiveIntegerField()),
                ('position', models.CharField(choices=[('A', 'AWD'), ('F', 'FWD'), ('R', 'RWD')], max_length=1)),
                ('image', models.ImageField(upload_to='car/')),
                ('status', models.BooleanField(default=False)),
                ('manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pordz.manufacture')),
            ],
        ),
    ]
