# Generated by Django 4.2.6 on 2023-10-14 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, unique=True, verbose_name='Brand')),
                ('hp', models.PositiveIntegerField(verbose_name='HorsePower')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='About car')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name': 'Car',
                'verbose_name_plural': 'Cars',
            },
        ),
    ]
