# Generated by Django 4.2.6 on 2023-10-14 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0002_car_country_alter_car_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='Brand'),
        ),
    ]
