# Generated by Django 4.2.6 on 2023-10-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0008_animal_created_at_animal_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='color',
            field=models.CharField(max_length=20, verbose_name='Color'),
        ),
    ]
