# Generated by Django 4.2.6 on 2023-10-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0009_alter_animal_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=20)),
                ('product', models.CharField(max_length=20, verbose_name='What product did you order?')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Rate us from 1 to 10')),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': 'Delivery',
                'verbose_name_plural': 'Delivery',
            },
        ),
    ]
