# Generated by Django 4.2.6 on 2023-10-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0013_alter_review_options_alter_review_reviewer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Flower Name')),
                ('petal_color', models.CharField(max_length=30, verbose_name='Petal Color')),
                ('stem_color', models.CharField(max_length=30, verbose_name='Stem Color')),
                ('season', models.CharField(max_length=30, verbose_name='Bloom Season')),
            ],
            options={
                'verbose_name': 'Flower',
                'verbose_name_plural': 'Flowers',
            },
        ),
    ]
