# Generated by Django 4.2.6 on 2023-10-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0020_alter_person_age_alter_person_birth_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='person',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='birth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
