# Generated by Django 4.2.6 on 2023-11-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_sell', '0003_alter_carsell_photo1_alter_carsell_photo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsell',
            name='currency_choose',
            field=models.CharField(choices=[('AMD', 'AMD'), ('RUB', 'RUB'), ('EUR', 'EUR'), ('USD', 'USD')], max_length=3, verbose_name=''),
        ),
    ]
