# Generated by Django 4.2.6 on 2023-11-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_subcategory_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='upgrated_at',
            new_name='upgraded_at',
        ),
        migrations.RenameField(
            model_name='subcategory',
            old_name='upgrated_at',
            new_name='upgraded_at',
        ),
    ]
