# Generated by Django 4.2.6 on 2023-10-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0004_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profession',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
