# Generated by Django 4.2.6 on 2023-10-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0005_person_profession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10, verbose_name='Gender of animal')),
                ('animal_owner_name', models.CharField(blank=True, max_length=20, null=True)),
                ('animal_owner_number', models.PositiveIntegerField(max_length=20)),
                ('city', models.CharField(max_length=30, verbose_name='City')),
                ('breed', models.CharField(max_length=15)),
                ('age_animal', models.PositiveSmallIntegerField()),
                ('description', models.TextField(verbose_name='Problem of animal')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='Gender: MALE or FEMALE'),
        ),
    ]
