# Generated by Django 4.2.6 on 2023-10-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstproject', '0006_animal_alter_person_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'verbose_name': 'Animal', 'verbose_name_plural': 'Animals'},
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='age_animal',
            field=models.PositiveSmallIntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_owner_number',
            field=models.PositiveIntegerField(verbose_name='Number'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Problem of animal'),
        ),
    ]
